// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQvwKjxUHej68HLzt1n100Uk4lP_axLs',
    appId: '1:1034182442907:web:cfae32cb62531e236aab3e',
    messagingSenderId: '1034182442907',
    projectId: 'notification-premium-store',
    authDomain: 'notification-premium-store.firebaseapp.com',
    storageBucket: 'notification-premium-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGlLmqpNolDJXZ4Wu8apdXf8aZNI8iKq4',
    appId: '1:1034182442907:android:440b6532d03b26a66aab3e',
    messagingSenderId: '1034182442907',
    projectId: 'notification-premium-store',
    storageBucket: 'notification-premium-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUcl5oxJXxhSPfpCs41_jNXeTrSzGf1wo',
    appId: '1:1034182442907:ios:f8263f9438c233d76aab3e',
    messagingSenderId: '1034182442907',
    projectId: 'notification-premium-store',
    storageBucket: 'notification-premium-store.firebasestorage.app',
    iosBundleId: 'com.example.premiumStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUcl5oxJXxhSPfpCs41_jNXeTrSzGf1wo',
    appId: '1:1034182442907:ios:f8263f9438c233d76aab3e',
    messagingSenderId: '1034182442907',
    projectId: 'notification-premium-store',
    storageBucket: 'notification-premium-store.firebasestorage.app',
    iosBundleId: 'com.example.premiumStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKQvwKjxUHej68HLzt1n100Uk4lP_axLs',
    appId: '1:1034182442907:web:5a647d9fa31361d96aab3e',
    messagingSenderId: '1034182442907',
    projectId: 'notification-premium-store',
    authDomain: 'notification-premium-store.firebaseapp.com',
    storageBucket: 'notification-premium-store.firebasestorage.app',
  );
}
